### ISSUE TITLE
PRIME battle solution does not work: eu mystel

### ISSUE THREAD

**Issue by lidel97** [TeraProxy/Essentials#8] opened 2018-07-25 12:46 UTC
Even if i set "false" the nostrum option, module doesn't work correctly. what have i to do? thanx

**Comment by aurelius88** [comment] 2018-08-21 19:16
Yeah, i had the same issue and fixed it for myself.
The problem is in function "nostrum": 
`	function nostrum() {
		clearTimeout(timeoutNostrum)
		if(game.isIngame && game.me.alive && !game.isInLoadingScreen && !game.me.mounted && !game.contract.active && !game.me.inBattleground && (slot || !ELITE) && !iAmInvincible)
			timeoutNostrum = setTimeout(useNostrum, nextUse - Date.now())
	}`

**Comment by aurelius88** [comment] 2018-08-21 19:38
Yeah, I had the same issue, but fixed it for myself. The problem is in function "**nostrum**". It is checking for a `slot`, but with elite/club there is no slot of the elite/club bar, because there is no bar. So this is always false and nostrum is never used. Replacing `slot` with `(slot || !ELITE)` fixes it. Now, it only checks for slot if it's also elite.

Old function which does not work for non-elite/non-club member:
```js
	function nostrum() {
		clearTimeout(timeoutNostrum)
		if(game.isIngame && game.me.alive && !game.isInLoadingScreen && !game.me.mounted && !game.contract.active && !game.me.inBattleground && slot && !iAmInvincible)
			timeoutNostrum = setTimeout(useNostrum, nextUse - Date.now())
	}
```
New function including fix:
```js
	function nostrum() {
		clearTimeout(timeoutNostrum)
		if(game.isIngame && game.me.alive && !game.isInLoadingScreen && !game.me.mounted && !game.contract.active && !game.me.inBattleground && (slot || !ELITE) && !iAmInvincible)
			timeoutNostrum = setTimeout(useNostrum, nextUse - Date.now())
	}
```

Either replace the complete function with the new one here or replace `slot` with `(slot || !ELITE)` inside this function. And make sure to disable auto update by renaming/deleting `module.json` (I prefer adding an ending like ".bkup" => e.g. module.json.bkup) when using Caali's Tera Proxy until the fix is included here.

**Comment by TeraProxy** [comment] 2018-08-26 21:38
thx aurelius88. you can probably tell I'm still using elite status, haha.
The fix is live now.

**Closed as completed by TeraProxy** 2018-08-26 21:38 UTC
